apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
  # annotations:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/NoMoosey/cluster-moose
    targetRevision: HEAD
    path: kubernetes/rr-fam/sonarr
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: rr-fam
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
