---

- name: Add the cert-manager helm repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Add cert-manager CRDs
  kubernetes.core.k8s:
    state: present
    src: https://github.com/cert-manager/cert-manager/releases/download/{{certmgr_chart_version }}/cert-manager.crds.yaml
    wait: yes

- name: Install cert-manager helm chart
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: "{{ certmgr_chart_version }}"
    release_namespace: cert-manager
    create_namespace: yes
    values_files:
      - "{{ playbook_dir }}/../kubernetes/cert-manager/values.yaml"
    wait: yes
    atomic: yes

- name: Apply Cloudflare token secret
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../../configs/kubernetes/cert-manager/secret-token.yaml"

- name: Apply staging issuer
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../kubernetes/cert-manager/issuers/letsencrypt-staging.yaml"
    wait: yes

- name: Apply staging certificate
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../kubernetes/cert-manager/certificates/staging/kube-crowlight-com.yaml"
    wait: yes

- name: Apply production issuer
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../kubernetes/cert-manager/issuers/letsencrypt-production.yaml"
    wait: yes

- name: Apply production certificate
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../kubernetes/cert-manager/certificates/production/kube-crowlight-com.yaml"
    wait: yes

