apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-pool-ad
  namespace: metallb
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb
spec:
  addresses:
  - 10.1.2.140-10.1.2.159
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-advert
  namespace: metallb
spec:
  ipAddressPools:
  - default-pool