kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: folding-work-pvc
  namespace: random
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi