---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-crowlight-com
  namespace: default
spec:
  secretName: kube-crowlight-com-staging-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.kube.crowlight.com"
  dnsNames:
  - "kube.crowlight.com"
  - "*.kube.crowlight.com"
