apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: kube-prom
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: 10.1.2.182