apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
  namespace: rr-fam
spec:
  serviceName: radarr
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: ghcr.io/linuxserver/radarr:latest
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        ports:
        - containerPort: 7878
          name: web
        volumeMounts:
        - name: backups
          mountPath: /config/Backups
        - name: config
          mountPath: /config
          readOnly: false
        - name: media
          mountPath: /movies
          readOnly: false
        - name: downloads
          mountPath: /downloads
          readOnly: false
        # livenessProbe:
        #   tcpSocket:
        #     port: 7878
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # readinessProbe:
        #   tcpSocket:
        #     port: 7878
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "2000m"
      # initContainers:
      # - name: radarr-init
      #   image: nomoosey/radarr-init:latest
      #   volumeMounts:
      #   - name: config
      #     mountPath: /config_mount
      #   command: ['bash', '-c', "sleep 10; cp -rn /init_config/radarr/* /config_mount/;"]
      volumes:
      - name: backups
        nfs:
          server: 10.1.0.200
          path: /volume1/lab/backups/radarr
      - name: downloads
        nfs:
          server: 10.1.0.200
          path: /volume1/lab/media
      - name: media
        nfs:
          server: 10.1.0.200
          path: /volume1/media/movies
      - name: config
        persistentVolumeClaim:
          claimName: radarr-pvc
