apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-helm
  namespace: argocd
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.3.1
    helm:
      releaseName: longhorn
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system