---

- hosts: all
  gather_facts: true
  #ignore_errors: yes
  become: false
  roles:
  - role: setup
  - role: cert-manager
    tags: 
    - 'linode'
  - role: reflector
    tags: 
    - 'linode'
  - role: traefik
    tags: 
    - 'linode'
  - role: storage
    tags: 
    - 'storage'
    - 'linode'
  - role: monitoring
    tags: 
    - 'linode'
